# Set theme
remote_theme: daviddarnes/alembic


# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji


# Site settings
url: 'https://bit1029public.github.io/'
baseurl: ''
title: '1029 Deep Reinforcement Learning Group'
description: 'A research group at Beijing Institute of Technology'
permalink: pretty
logo: "/images/logo.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Publications
  url: /publications/
# - title: Blog
#   url: /blog/
- title: Join
  url: /apply/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  home:
    feature_text: |
      ## 1029 Deep Reinforcement Learning Group @
      Beijing Institute of Technology
      <br>
      <br>
    feature_image: "/images/wallpaper/bit2.jpg"
  pages:
    # feature_text: |
    #   ## Human & Machine Learning Lab
    #   A research lab at New York University
    # feature_image: "https://picsum.photos/2560/600?image=872"
  posts:
    title: Blog
    output: true
    description: "Read about the latest research from HMLL"
theme: jekyll-theme-cayman
